[package]
name = "pestle"
version = "0.1.0"
edition = "2021"
license = "0BSD"
description = "typed AST facade for the pest parser"
repository = "https://github.com/a6f/pestle"
readme = "README.md"

[lib]
proc-macro = true

[dependencies]
pest_meta = "2"
proc-macro2 = "1"
quote = "1"
syn = "2"
