[package]
name = "pestle"
version = "0.1.0"
edition = "2021"
default-run = "pestle"

[dependencies]
bumpalo = { version = "3.16.0", features = ["collections"] }
pest = "2.7.15"
pest_derive = "2.7.15"
pest_meta = "2.7.15"

[[bin]]
name = "test"
